// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8N0gZUOBfBzH71wSblq1EiUPn7XeRyA',
    appId: '1:737325233804:ios:bb1baacadf2ff6c6c46da9',
    messagingSenderId: '737325233804',
    projectId: 'runnershigh-8d162',
    storageBucket: 'runnershigh-8d162.appspot.com',
    iosBundleId: 'com.example.runnersHigh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn8N0gZUOBfBzH71wSblq1EiUPn7XeRyA',
    appId: '1:737325233804:ios:bb1baacadf2ff6c6c46da9',
    messagingSenderId: '737325233804',
    projectId: 'runnershigh-8d162',
    storageBucket: 'runnershigh-8d162.appspot.com',
    iosBundleId: 'com.example.runnersHigh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmg83kR00qQUwY5tufTT31GcvmLY07-Rg',
    appId: '1:737325233804:web:adea360f405ba5e3c46da9',
    messagingSenderId: '737325233804',
    projectId: 'runnershigh-8d162',
    authDomain: 'runnershigh-8d162.firebaseapp.com',
    storageBucket: 'runnershigh-8d162.appspot.com',
    measurementId: 'G-7SP4370J6P',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmg83kR00qQUwY5tufTT31GcvmLY07-Rg',
    appId: '1:737325233804:web:adea360f405ba5e3c46da9',
    messagingSenderId: '737325233804',
    projectId: 'runnershigh-8d162',
    authDomain: 'runnershigh-8d162.firebaseapp.com',
    storageBucket: 'runnershigh-8d162.appspot.com',
    measurementId: 'G-7SP4370J6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASqKiw2HjbLLIzipG2ZKWEsdeCqU4DowI',
    appId: '1:737325233804:android:8c846e6bbd2fdfb3c46da9',
    messagingSenderId: '737325233804',
    projectId: 'runnershigh-8d162',
    storageBucket: 'runnershigh-8d162.appspot.com',
  );

}